# Generated by Django 5.0.2 on 2024-03-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_auth_token_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('fem', 'female')], default=None, max_length=3),
            preserve_default=False,
        ),
    ]
