# Generated by Django 5.0.2 on 2024-03-14 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='thkr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thkr', models.CharField(max_length=255)),
                ('repeat', models.IntegerField()),
                ('auth_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
