# Generated by Django 5.0.2 on 2024-03-14 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_thkr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thkr',
            old_name='auth_token',
            new_name='user',
        ),
    ]
