# Generated by Django 5.0.2 on 2024-03-14 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_auth_token_thkr_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thkr',
            old_name='user',
            new_name='user_id',
        ),
    ]
