# Generated by Django 5.0.2 on 2024-03-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_user_thkr_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thkr',
            name='thkr',
            field=models.TextField(max_length=255),
        ),
    ]
